### ISSUE TITLE
Failed to compile with 3 errors

### ISSUE THREAD

**Issue by andrewlam-mbaex** [creativetimofficial/vue-light-bootstrap-dashboard#29]
"version": "2.0.0"

I am getting the below errors when I run `npm run dev`

> ERROR  Failed to compile with 3 errors
> 
> This dependency was not found:
> 
> * core-js/modules/es6.regexp.to-string in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Cards/ChartCard.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Inputs/BaseRadio.vue?vue&type=script&lang=js& and 1 other
> 
> To install it, you can run: npm install --save core-js/modules/es6.regexp.to-string

Then I followed the instruction to run `npm install --save core-js/modules/es6.regexp.to-string`, but could not install.

> npm ERR! code ENOLOCAL
> npm ERR! Could not install from "core-js\modules\es6.regexp.to-string" as it does not contain a package.json file.

How can I solve this error?

**Comment by Domynos** [comment]
@andrewlam-mbaex Did you found any solution on this ? Node version maybe ? Thx

**Comment by andrewlam-mbaex** [comment]
@Domynos No I did not, I've instead switch to use vue-element-admin template with better support.

**Comment by Domynos** [comment]
@andrewlam-mbaex 
Thanks for your answer.
Ok, vue-element-admin looks great :+1:

**Comment by Wisdom132** [comment]
what you have to do is to go to any of your previous vue project >go to the node modules folder >copy a folder title core-js,now move to creative time project >go to the node modules folder delete the core-js folder and paste the folder you copied.then run npm run dev or npm run serve

**Comment by kimneto** [comment]
`npm i core-js`

**Comment by anhnt4288** [comment]
> what you have to do is to go to any of your previous vue project >go to the node modules folder >copy a folder title core-js,now move to creative time project >go to the node modules folder delete the core-js folder and paste the folder you copied.then run npm run dev or npm run serve

thanks, i have fixed it

**Comment by MrEduar** [comment]
This error is still present. And the previous solutions did not work.
